### ISSUE TITLE
Failed to initialize bridge

### ISSUE THREAD

**Issue by xrmdj** [bocajthomas/SE-Extended#141]
### Description

I followed the installation guide for non rooted device and used the pre-patched apk but still would get the error message every time I open it: SE extended failed to initialize. Please check logs for more details. 

### Reproduction steps

1. Open Snapchat
2. See Error.

### Logs

java.lang.UnsatisfiedLinkError: LspModuleClassLoader[module=/data/user/0/com.snapchat.android/cache/lspatch/me.rhunk.snapenhance/3027962436.apk, org.lsposed.lspd.util.LspModuleClassLoader[DexPathList[[dex file "InMemoryDexFile[cookie=[0, -5476376647887682800, -5476376647887678992]]"],nativeLibraryDirectories=[/data/user/0/com.snapchat.android/cache/lspatch/me.rhunk.snapenhance/3027962436.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]] couldn't find "lib5d5f8a3169b16d06.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1765)
	at me.rhunk.snapenhance.nativelib.NativeLib.initOnce(Unknown Source:11)
	at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:114)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:11)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$init$3.invokeSuspend(Unknown Source:189)
	at w2.a.resumeWith(Unknown Source:8)
	at V2.s.u(Unknown Source:6)
	at Q2.a.resumeWith(Unknown Source:22)
	at w2.a.resumeWith(Unknown Source:31)
	at V2.s.u(Unknown Source:6)
	at Q2.a.resumeWith(Unknown Source:22)
	at w2.a.resumeWith(Unknown Source:31)
	at Q2.G.run(Unknown Source:114)
	at Q2.Q.T(Unknown Source:140)
	at Q2.B.y(Unknown Source:104)
	at Q2.B.z(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:6)
	at me.rhunk.snapenhance.core.XposedLoader.handleLoadPackage$lambda$0(Unknown Source:17)
	at me.rhunk.snapenhance.core.XposedLoader.a(Unknown Source:0)
	at me.rhunk.snapenhance.common.messaging.a.invoke(Unknown Source:166)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1233)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1403)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6867)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2219)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)

### Snapchat Version

12.81.0.44

### SE Extended Version

1.0.0 (100) - c3d865c

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Can you send me the .zip 

Simply `Open SE-Extended`, then `Tap The Bug  Icon` ( next to the then `Tap the 3 dots` then `Tap Export` then save and send here by pressing `Paste, drop, or click to add files`

**Comment by xrmdj** [comment]
[SE Extended-logs-1731087731596.zip](https://github.com/user-attachments/files/17682292/SE.Extended-logs-1731087731596.zip)

**Comment by bocajthomas** [comment]
Can you redo the process.

**Comment by xrmdj** [comment]
I did and still got the same error :/

**Comment by bocajthomas** [comment]
cant reproduce
